### ISSUE TITLE
How to hide default locale in url?

### ISSUE THREAD

**Issue by juanm4** [mydnic/Laravel-Multilingual-SEO-Example#1]
Hi, I have followed this tutorial and it have worked succesfully. But I have a doubt. How I can hidde the defautl locale in url?, I mean, if my default locale is 'en', I want that when I writte /home, the url not change to /en/home...

Thanks!

**Comment by mydnic** [comment]
Hello
This is beyond the scope of the tutorial because it is not recommened for SEO purposes.
It's better to always have the locale code in the URL for multilingual websites.

If you want to accomplish that anyway, you should first comment or delete the Language.php Middleware.

You also need to tweak the RouteServiceProvider the make the prefix optional. And finally update the AppServiceProvider to apply fallback locale when no Request segment is provided.

Hope it helps
